In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
%matplotlib inline

from urllib.request import urlopen
from bs4 import BeautifulSoup

url = "http://www.hubertiming.com/results/2017GPTR10K"

html = urlopen(url)

soup = BeautifulSoup(html, "html.parser")
type(soup)
#bs4.BeautifulSoup

text = soup.get_text()
#print(soup.text)

#all_links = soup.find_all('a')
#for link in all_links:
#    print(link.get("href"))

rows = soup.find_all('tr')
#print(rows[:10])
for row in rows:
    row_td = row.find_all('td')
#print(row_td)
#str_cells = str(row_td)
#cleantext=BeautifulSoup(str_cells, "html.parser").get_text()
#print(cleantext)
#type(row_td)

#Regular Expression Test 

list_rows = []
for row in rows:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 =(re.sub(clean, '',str_cells))
    list_rows.append(clean2)
type(clean2)

df = pd.DataFrame(list_rows)
#df.head(10)
df1 = df[0].str.split(',',expand=True)
#df1[0] = df1[0].str.split('[')
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,[],None,None,None,None,None,None,None,None,None,None,None,None,None
1,[Finishers:,577],None,None,None,None,None,None,None,None,None,None,None,None
2,[Male:,414],None,None,None,None,None,None,None,None,None,None,None,None
3,[Female:,163],None,None,None,None,None,None,None,None,None,None,None,None
4,[],None,None,None,None,None,None,None,None,None,None,None,None,None
5,[1,814,JARED WILSON,M,TIGARD,OR,36:21,5:51,1 of 414,M 36-45,1 of 152,0:03,36:24,]
6,[2,573,NATHAN A SUSTERSIC,M,PORTLAND,OR,36:42,5:55,2 of 414,M 26-35,1 of 154,0:03,36:45,INTEL TEAM F]
7,[3,687,FRANCISCO MAYA,M,PORTLAND,OR,37:44,6:05,3 of 414,M 46-55,1 of 64,0:04,37:48,]
8,[4,623,PAUL MORROW,M,BEAVERTON,OR,38:34,6:13,4 of 414,M 36-45,2 of 152,0:03,38:37,]
9,[5,569,DEREK G OSBORNE,M,HILLSBORO,OR,39:21,6:20,5 of 414,M 26-35,2 of 154,0:03,39:24,INTEL TEAM F]